### ISSUE TITLE
for lipki

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/MCPE#1]
@lipki can you work on this

i will work on some more mod support

**Comment by tobyplowy** [comment]
@lipki and if you want to do this Please remember you have to edit The images that already in the pack 
Do not put images from outside of the pack in or replace them

If you don't Just edit the images but instead replace things (even if they have the same name)
Or put stuff in and rename it It will not work You are forced to edit The images

**Comment by chengzzi89** [comment]
hi

**Comment by tobyplowy** [comment]
@chengzzi89 hi

**Comment by lipki** [comment]
Hello, welcome.
Thank you for visiting us.
As you can see in the conversation, nobody takes care of the pack MCPE.
I do not have smart-phone compatible or tablet.

As you seem to be interested, do you want to take care of it?

The job :
Create the missing textures, suggest them here, [via an issue](https://github.com/SummerFields/MCPE/issues/new).
Make the first package, and explain how it works.
Also offer textures for other version of the Summerfields, and give your advice everywhere.

No pressure :D

**Comment by chengzzi89** [comment]
In the MCPE version, I added a side texture to shulker! In this case, it will be very reasonable display in the backpack!

**Comment by chengzzi89** [comment]
In the MCPE version, I added a side texture to shulker! In this case, it will be reasonable display in the backpack!

**Comment by lipki** [comment]
I give you a demonstration for this case.
First : make a new issue : #2

**Comment by chengzzi89** [comment]
For sale to the MCPE store for sale, do you agree?😃
![_20170602_061530](https://user-images.githubusercontent.com/28303754/26938565-1ed9dff0-4ca7-11e7-97d6-a4202e47ee34.jpg)

**Comment by tobyplowy** [comment]
@chengzzi89 I do agree but i think it would be better if it was registered under my account or @lipki s account (we are both a long and big part of this project lipki and I so that's why, lipki more than I am but I have more free time than him)

@lipki what do you think of this?

**Comment by tobyplowy** [comment]
Also We should probably also make Summerfields free if possible (also this store is a ripoff I was already wondering when Microsoft wuld fuck up Minecraft just like rareware and the menny other games)

**Comment by lipki** [comment]
I will look, it will be free anyway, and if it is not possible ben tampis.

**Comment by chengzzi89** [comment]
@lipki @tobyplowy The original idea is to put the MC official store to do the paid resource package, but now think about it, there may be no one to download this pe texture! So I respect your decision!😃

**Comment by tobyplowy** [comment]
@chengzzi89 this is not about money it has never been it will never be
It's about creativity and continuing a project that we all love

**Comment by lipki** [comment]
+1
