### ISSUE TITLE
Rotated textures

### ISSUE THREAD

**Issue by pfccalico** [SummerFields/MCPE#16]
Textures are being automatically rotated and this can't be turned off in game. the java method for using UV tag and x and y rotation notation in the blockstates file doesn't apply to bedrock as it doesn't use the blockstates system as far as i am aware. I have tried forcing the isotropic state to be true in the blocks.json but it doesn't seem to work.

**Comment by pfccalico** [comment]
fixed

for future reference, ensure the block that needs adjusting has an entry in both terrain_textures.json and blocks.json.

**Comment by lipki** [comment]
OK, thanks.
